version: '3.5'
services:
    processing:
        image: 'levan92/covreid'
        stdin_open: true
        tty: true
        volumes: 
            - $HOME/Documents/personal_projects/Harvardx_CS50W/Flight/src:/home/src
        
    db:
        image: 'postgres'

        environment:
            - TZ=Asia/Singapore
            - POSTGRES_DB=mydatabase
            - POSTGRES_HOST=localhost
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_PORT=5432
        ports:
            - '25432:5432'